[package]
name = "lambdash"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lambdash"
path = "src/main.rs"

[dependencies]
crossterm = "0.28.1"
serde = { version = "1.0.216", features = ["derive"] }
toml = "0.8.19"
